/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mihailo_dikanovic_shoppinglist_JNIexample */

#ifndef _Included_mihailo_dikanovic_shoppinglist_JNIexample
#define _Included_mihailo_dikanovic_shoppinglist_JNIexample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mihailo_dikanovic_shoppinglist_JNIexample
 * Method:    sumPrices
 * Signature: (Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_mihailo_dikanovic_shoppinglist_JNIexample_sumPrices
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
